#!/bin/bash -x

OIFS="$IFS"
IFS=":"

includes="$WAKE_IP_RESOURCE_INCLUDES"
include_args=( )
for include in $includes; do
  include_args+=( +incdir+"$include" )
done

files="$WAKE_IP_RESOURCE_FILES"
file_args=( )
for file in $files; do
  file_args+=( "$file" )
done

filelists="$WAKE_IP_RESOURCE_FILELISTS"
filelist_args=( )
for filelist in $filelists; do
 filelist_args+=(-F "$filelist")

libraries="$WAKE_IP_RESOURCE_LIBRARIES"
library_args=( )
for library in $libraries; do
  library_args+=( -y "$library" )
done

static_libs="$WAKE_IP_HDL_SIM_STATIC_LIBRARIES"
static_lib_args=( )
for static_lib in $static_libs; do
  static_lib_args+=( "$static_lib" )
done

pli_tabs="$WAKE_IP_HDL_SIM_PLI_TAB"
pli_tab_args=( )
for pli_tab in $pli_tabs; do
  pli_tab_args+=( -P "$pli_tab" )
done

IFS="$OIFS"

vcs "${file_args[@]}" "${include_args[@]}" "${filelist_args[@]}" "${library_args[@]}" "${static_lib_args[@]}" "${pli_tab_args[@]}" "$@"
